use_frameworks!

platform :ios, '12.0'

target 'YDRootNavigationController_Example' do
  pod 'YDRootNavigationController', :path => '../'

  target 'YDRootNavigationController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
